### ISSUE TITLE
Usage rights for the midis

### ISSUE THREAD

**Issue by KitMakesGamesIGuess** [AyHa1810/touhou-midi-collection#2]
Hi, sorry to bother, but I'm wondering what the usage rights for the midis are in the collection, if they're allowed to be used, modified, etc. for use in games, making a touhou game jam game and need to know if i'll be able to use any of these midis as a jumping off point to make music for it, thanks ^^

**Comment by AyHa1810** [comment]
Apologies for late reply, I've now added usage policy section in the README file, so you can refer to it.
